### ISSUE TITLE
doesn't work well with nodemon

### ISSUE THREAD

**Issue by morganrallen** [AgentME/browserify-hmr#1]
I haven't had a chance to dive in deeply but it appears `hmr` spawns it's own process to manage the websockets server. When `nodemon` detects a code change and restarts the main process, `hmr` tries to listen on 3123 again, which is still in use by the previous instance.

**Comment by AgentME** [comment]
I'm not sure I understand how watchify and nodemon would be used together. Can you create an example that shows the issue?

I see that if I send SIGTERM to the main process, the child process doesn't die. I can fix that soon but I don't know if it will fix the nodemon case without testing it.

**Comment by morganrallen** [comment]
I use both in my dev process, `watchify` used in the module form can prebuilt the build before I reload a page, just speeds things up.

**Comment by AgentME** [comment]
I just put version 0.2.2 up which should fix this issue. If the child process loses connection, it exits itself. (And if the builder process loses connection to the socket server, an error is triggered.)

**Comment by morganrallen** [comment]
nice!

On Sun, Aug 30, 2015 at 3:36 PM, Chris Cowan <notifications@github.com>
wrote:

> I just put version 0.2.2 up which should fix this issue. If the child
> process loses connection, it exits itself. (And if the builder process
> loses connection to the socket server, an error is triggered.)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/AgentME/browserify-hmr/issues/1#issuecomment-136211083>
> .
>



-- 
http://ithoughtyouweretherobot.com
Metal and Wire

http://nolonelyguineapigs.com/
Wandering and Rambling

http://morglog.org
Old and Neglected.

-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: OpenPGP.js v.1.20121007
Comment: http://openpgpjs.org

xsBNBFG3btUBB/9+/WJNOSIuc/praKPaPOweqXV5s7PGRD+HAnNWF/19YAY3
AFtfeoelhhY4sMJoobTaJzcZojznZ1kl/7UuuYCnbJO3Z9kaSMVrVxEZMSLe
YmW8Hc4ZsTnl9f05DQFy8ABpAvMLmXJQXh63BbfzjFqNbSWQfLhrubSM2Elq
xmN6EsmRyAuEeYlSnal+Di2MlViohpCbbagE2D6AZTUECIamTib6+DuLG4XO
b4GGKHR9TXu2qS1VH6hqcvdEz2MDE5OqZzAnBgcF2dvcOdTk9gAOoR1T+qKj
IJtg2X0ETbxcPqEXQoXE8VrxN0MLT5JQKTg26+csU4P2w0rEWsUsJombABEB
AAHNJU1vcmdhbiBBbGxlbiA8bW9yZ2FucmFsbGVuQGdtYWlsLmNvbT7CwFwE
EAECABAFAlG3btwJEG9pFLKaVEfeAAD7hwf+K8LN/kfgi8GTRLiTcuM+hSbm
uAeiBY+VaJIQFLzoFlt8A0hBlLNPFNNmUDxdPrMErdHgZ7HtJW/6RANuBTti
5hr3EBguH1GQyK7BbUqJGvaEX4UNRej3uyX3ufXDsIB/3NsKaTyyu+SO0+Hv
Cn2DwmlfSXcPhoarx6Turizn/WwgtTN3tqrMWxxiCKWydLH5xYuz+23BLMdc
oF/zkbF+7ddFhmyfiFh4Ej9//tsfwPj2cACU3uLTrcwCo7IxUtkrqMF/fhlm
LEqjhzDDjq9v7GNWb/5xB2xgTaucJ7/ljuS8nPlZqwCI8NlTgSqC8nyVLyjS
yVtOzkItcS0UqyW1Mg==
=V/Ia
-----END PGP PUBLIC KEY BLOCK-----
