### ISSUE TITLE
hmr client tries to connect to 2123 regardless of --port option

### ISSUE THREAD

**Issue by Gozala** [AgentME/browserify-hmr#11]

**Comment by AgentME** [comment]
The --port option controls what port the local socket server listens on, but it doesn't control what port the bundle tries to connect to. You need to change the --url setting to set that.

In previous versions, the --port option used to be automatically determined from the --url setting, but the number of settings that automagically changed their default values based on other settings was getting pretty confusing and I decided to drop all of those in favor of making the user be explicit. If the readme doesn't explain this well, please feel free to suggest improvements to it!
