### ISSUE TITLE
Updatest printed to browser console but not actually happening.

### ISSUE THREAD

**Issue by Industrial** [AgentME/browserify-hmr#16]
Hi.

I'm trying to set up this project with HMR but I can't seem to get file updates actually injected/changing the browser.

https://gist.github.com/Industrial/36c747860fad05259a2b

**Comment by AgentME** [comment]
Are the files that you want to be live-reloaded using `module.hot` or defining React components? If not, then the "Updated modules" log line is being caused by this bug: https://github.com/AgentME/browserify-hmr/issues/14. You'll need to

**Comment by Industrial** [comment]
I got the problem fixed.

We were using plain functions as react components, and not subclasses of React.Component.

**Comment by AgentME** [comment]
Right, react-transform-hmr doesn't currently recognize components as functions: https://github.com/gaearon/react-transform-hmr/issues/6
