### ISSUE TITLE
Updating source maps

### ISSUE THREAD

**Issue by Calvein** [AgentME/browserify-hmr#2]
It might be more of a question that an issue (or it might not be related to browserify-hmr) but it looks like source maps aren't updating with browserify-hmr, is there a way to have them updating somehow ?

**Comment by AgentME** [comment]
As far as I can tell, browserify-hmr handles sourcemaps right. It seems like browsers have issues with loading new sourcemaps for files: https://github.com/gaearon/react-hot-loader/issues/180.

**Comment by Calvein** [comment]
That's good to know and annoying at the same time :/
I'm closing the issue since it's not related to browserify-hmr.
