### ISSUE TITLE
Problem with engine-io

### ISSUE THREAD

**Issue by Industrial** [AgentME/browserify-hmr#23]
Hi.

I'm having this problem with engine.io-client:

http://i.imgur.com/Kbw6a1l.png

it's on line 214 in the screenshot, seems to return undefined.

**Comment by AgentME** [comment]
I can't reproduce this issue. I'm curious about what version of socket.io-client you're using. Can you post the output of `npm ls` is from within your project?

**Comment by Industrial** [comment]
I'm afraid my setup is a little complicated;

I am building my gulp setup (including browserify) as a NPM module so that I don't have to repeat the same gulp config in all the projects I use it with. It supports server and client code and is set to be both DRY and configurable... [Here are the browserify tasks](https://github.com/Industrial/id-builder/blob/49e5819b96f7e3410a1055a6242d7611a9eef4a7/src/tasks/browserify.js#L94) and the [package.json](https://github.com/Industrial/id-builder/blob/49e5819b96f7e3410a1055a6242d7611a9eef4a7/package.json). This version is not released on NPM yet since it's not stable. I'm using `npm link` to use it in a "full-blown" [project](https://github.com/Industrial/test-loopback/tree/61200015486713a1ec708db296db74ebbec95b3a) to test all the aspects of the setup.

**Comment by AgentME** [comment]
Did you solve the issue? I've been able to reproduce it now.

**Comment by Industrial** [comment]
I didn't solve it yet but it's definitely not a problem with browserify-hmr. It's the way I am trying to split up the bundles into a node_modules.bundle.js and app.bundle.js. There's some stuff going wrong with the bundling so the node_modules doesn't include all code and some modules are pointing to themselves (infinite loop).

**Comment by AgentME** [comment]
Bundle splitting isn't something I've tested with browserify-hmr. If your project works when you disable browserify-hmr, then it's probably browserify-hmr's fault.
