### ISSUE TITLE
support for websites running over https

### ISSUE THREAD

**Issue by royriojas** [AgentME/browserify-hmr#6]
Hi the current website I have is running over ssl, and I had tweak the socket-server to make it work on ssl (with self signed certs). 

I was wondering if you might be interested in add the ssl option. 

I know I can make it work on http as well, but it would be nice not having to add the http vhost for the app I'm currently developing

**Comment by AgentME** [comment]
This has been implemented in 0.3.0.

**Comment by royriojas** [comment]
cool!
