### ISSUE TITLE
Do you know thermite

### ISSUE THREAD

**Issue by serapath** [AgentME/browserify-hmr#7]
https://github.com/omphalos/thermite/issues/1#issuecomment-143411319

**Comment by AgentME** [comment]
That looks like it's trying to be a more portable version of Amokify. Here's a similar discussion about [comparing Browserify-HMR and Amokify](https://github.com/caspervonb/amokify/issues/3). The HMR way is simple if your modules have an easily defined life cycle that you define yourself or use an add-on to (e.g. [react-transform-hmr](https://github.com/gaearon/react-transform-hmr)). I think HMR makes a good base for such tools. The Amokify and Thermite ways seem to be more about trying to automatically make arbitrary hot-patchable.
